name: Underilla
authors: [ Jeshuakrc, Hydrolien ]
version: '$version'
main: ${group}.spigot.Underilla
description: $description
api-version: "$apiVersion"
load: STARTUP

dependencies:
  server:
    VoidWorldGenerator:
      load: BEFORE
      required: true
    Chunky:
      load: BEFORE
      required: true